"""Research package for constrained multi-slope IS-NMF decay estimation."""

from .is_objective import gaussian_variance_nll, is_divergence
from .georg_baselines import (
    CommonSlopeEDCFit,
    DecayFitNetEstimate,
    ExternalDecayFitNet,
    band_energy_decay_curves,
    determine_common_decay_times,
    edc_to_equivalent_rir_power_amplitudes,
    fit_common_slope_edcs,
)
from .model import (
    exponential_atoms,
    exponential_variance,
    rate_to_t60,
    t60_to_rate,
)
from .preprocess import DecayFit, fit_coarse_decay, head_power, tail_power
from .rir import (
    SOFADatasetInfo,
    SRIRDatasetInfo,
    STFTPower,
    global_energy_onset,
    inspect_sofa_dataset,
    inspect_srir_dataset,
    load_sofa_channel,
    load_srir_channel,
    resample_rirs,
    rir_stft_power,
    select_stft_frames,
)
from .sage import (
    AmplitudeSAGEResult,
    DecaySAGEInit,
    DecaySAGEResult,
    DecaySAGEUpdateDiagnostics,
    amplitude_sage,
    decay_sage,
    init_decay_sage,
    pseudo_decay_sage,
    update_rates_bisection,
    update_rates_newton,
)
from .synth import (
    DecayData,
    sample_complex_gaussian,
    sample_multislope_data,
    sample_power,
    sample_simplex_amplitudes,
    sample_t60,
)

__all__ = [
    "AmplitudeSAGEResult",
    "CommonSlopeEDCFit",
    "DecayData",
    "DecayFitNetEstimate",
    "DecayFit",
    "DecaySAGEInit",
    "DecaySAGEResult",
    "DecaySAGEUpdateDiagnostics",
    "ExternalDecayFitNet",
    "SOFADatasetInfo",
    "SRIRDatasetInfo",
    "STFTPower",
    "amplitude_sage",
    "band_energy_decay_curves",
    "decay_sage",
    "determine_common_decay_times",
    "edc_to_equivalent_rir_power_amplitudes",
    "exponential_atoms",
    "exponential_variance",
    "gaussian_variance_nll",
    "fit_coarse_decay",
    "fit_common_slope_edcs",
    "global_energy_onset",
    "head_power",
    "init_decay_sage",
    "inspect_sofa_dataset",
    "inspect_srir_dataset",
    "is_divergence",
    "load_srir_channel",
    "load_sofa_channel",
    "pseudo_decay_sage",
    "rate_to_t60",
    "resample_rirs",
    "rir_stft_power",
    "select_stft_frames",
    "sample_complex_gaussian",
    "sample_multislope_data",
    "sample_power",
    "sample_simplex_amplitudes",
    "sample_t60",
    "tail_power",
    "t60_to_rate",
    "update_rates_bisection",
    "update_rates_newton",
]
